apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-e3tz
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr712-0075-0056-tenant/tkrw-pr712-0075-0056-app/devfile-sample-e3tz@sha256:017494ffef6e9446c9ba9db6dc3bf0d02bf6f61c5994803b6650a67cf759d337
        name: my-nodejs
        resources: {}
status: {}
